#!/bin/sh
#
# This loads the Database cache
#
java -Dlog4j.configuration="file:log4j.properties"  -cp target/XRTB-0.0.1-SNAPSHOT-jar-with-dependencies.jar com.xrtb.tools.DbTools $1 $2 $3 $4 $5 $6 $7 $8
